

/****** Object:  Database [DespesasMensais]    Script Date: 02/01/2021 13:32:08 ******/
CREATE DATABASE [DespesasMensais]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DespesasMensais', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DespesasMensais.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DespesasMensais_log', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DespesasMensais_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DespesasMensais].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DespesasMensais] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DespesasMensais] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DespesasMensais] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DespesasMensais] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DespesasMensais] SET ARITHABORT OFF 
GO

ALTER DATABASE [DespesasMensais] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DespesasMensais] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DespesasMensais] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DespesasMensais] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DespesasMensais] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DespesasMensais] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DespesasMensais] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DespesasMensais] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DespesasMensais] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DespesasMensais] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DespesasMensais] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DespesasMensais] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DespesasMensais] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DespesasMensais] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DespesasMensais] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DespesasMensais] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DespesasMensais] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DespesasMensais] SET RECOVERY FULL 
GO

ALTER DATABASE [DespesasMensais] SET  MULTI_USER 
GO

ALTER DATABASE [DespesasMensais] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DespesasMensais] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DespesasMensais] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DespesasMensais] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DespesasMensais] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DespesasMensais] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DespesasMensais] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DespesasMensais] SET  READ_WRITE 
GO


